### ISSUE TITLE
brew install fails because sudo chef-client

### ISSUE THREAD

**Issue by arukaen** [chef-cookbooks/homebrew#111] opened 2016-11-10 17:02 UTC
### Cookbook version
2.1.2

### Chef-client version
12.5.1

### Platform Details
Mac OSX 

### Scenario:
Bootstrapping a new node fails when I attempt to install packages because chef-client is running as sudo/root and as of November 1st, 2016 Homebrew has disabled running brew with root. This also occurs even when I have `default['homebrew']['owner'] = 'my username'`

https://github.com/Homebrew/brew/commit/eabdbde3f0b7d34de8233e8f886fea10d2922a9e

### Steps to Reproduce:
bootstrap a node or sudo chef-client with a recipe that installs a package using brew.

**Comment by bcg62** [comment] 2016-11-10 22:13
I have hit this in other circumstances. Some brew cask installs have sudo embedded like wireshark:

```
/usr/bin/sudo -E -- /usr/sbin/installer -pkg #<Pathname:/usr/local/Caskroom/wireshark/2.2.1/Wireshark 2.2.1 Intel 64.pkg> -target /
```

The work around used to be having chef run the install as root to negate the sudo call.

This now fails with 

```
"Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system."
```

Once you remove this and instal as the current user brew blows up expecting a tty to be available to prompt for a password

```
==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg #<Pathname:/usr/local/Caskroom/wireshark/2.2.1/Wireshark 2.2.1 Intel 64.pkg> -target /
 
==> Standard Output of failed command:
 
 
==> Standard Error of failed command:
sudo: no tty present and no askpass program specified
```

I'm not sure how to approach this, see other discussions here

https://github.com/Homebrew/brew/pull/1476
https://github.com/caskroom/homebrew-cask/issues/5667
https://github.com/caskroom/homebrew-cask/issues/19180

**Comment by bcg62** [comment] 2017-04-12 17:11
quick update, you can currently work around this outright failing by creating a sudo askpass script similar to this https://github.com/markcarver/mac-ssh-askpass and then setting it in your environment with $SUDO_ASKPASS - granted this will display a pop up to the user for their sudo password in the middle of a chef run... not ideal but it's enough for now

**Comment by tas50** [comment] 2017-04-20 01:11
Closing as a dupe of #105

**Closed by tas50** 2017-04-20 01:11 UTC
Labels: Type: Bug
